### ISSUE TITLE
Mime type in metadata

### ISSUE THREAD

**Issue by markkerzner** [markkerzner/FreeEed#124]
add a new column, filetype
provide a default mapping of mime to this new file type
http://help.dottoro.com/lapuadlp.php
http://www.freeformatter.com/mime-types-list.html
http://fileinfo.com/browse/

**Comment by alexee** [comment]
@markkerzner  I added new column, pre-filled with content types from files in test-data, will add remaining content-types later.

**Comment by alexee** [comment]
@markkerzner can you merge this?

**Comment by markkerzner** [comment]
Tested, merged, and closed
