### ISSUE TITLE
are there duplicates in metadata?

### ISSUE THREAD

**Issue by markkerzner** [markkerzner/FreeEed#125]
should not be

**Comment by alexee** [comment]
@markkerzner 
Hi Mark, can you explain a bit more what needs to be done here?

**Comment by markkerzner** [comment]
Yes, this means as follows. The same metadata field should not occur twice. This may be in the metadata setup, and also somewhere else. So just look at the output, the "load file". It is usually called part_0000 on Linux and Mac

**Comment by alexee** [comment]
Based on current code, there should not be duplicates. I added test for this case.

**Comment by markkerzner** [comment]
test code added to check for this
