### ISSUE TITLE
add message_id and referencess to metadata, also subject

### ISSUE THREAD

**Issue by markkerzner** [markkerzner/FreeEed#127]
https://www.jwz.org/doc/threading.html

https://github.com/maxogden/conversationThreading-js

**Comment by cyclomaticsegal** [comment]
The three fields required from email files:

An email Message object only has a few fields we are interested in for threading
String subject;          	
ID message_id;	// the ID of this message
ID *references;	// list of IDs of parent messages

The References field is populated from the ``References'' and/or ``In-Reply-To'' headers. If both headers exist, take the first thing in the In-Reply-To header that looks like a Message-ID, and append it to the References header.

If there are multiple things in In-Reply-To that look like Message-IDs, only use the first one of them: odds are that the later ones are actually email addresses, not IDs.

These ID objects can be strings, or they can be any other token on which you can do meaningful equality comparisons.

This item I think will require some experimentation on our part. I'd like to work with you on this one.

**Comment by alexee** [comment]
@markkerzner 

Added message_id and references, subject was already there. Please pull from my branch.

**Comment by markkerzner** [comment]
Tested and closed
