### ISSUE TITLE
Put metadata configuration into SQlite

### ISSUE THREAD

**Issue by markkerzner** [markkerzner/FreeEed#128]
It is in the config directory now, should be in SQLite. 

To test, remove (rename) the config file, and it should still work

**Comment by markkerzner** [comment]
Alex, if you check that we can take out the text file based configuration completely, then I will close this issue. This would make it totally clean.

**Comment by alexee** [comment]
@markkerzner 

Please pull from my branch and close.

**Comment by markkerzner** [comment]
confirmed
