### ISSUE TITLE
Not enough output

### ISSUE THREAD

**Issue by markkerzner** [markkerzner/FreeEed#130]
There should be over 2,000 files in the output with the current test data. But last I saw the load file, there were less than 200

**Comment by alexee** [comment]
I think it is correct, part file contains 129 lines, and I counted files in test data, and there are exactly 129 files.
Why do you think it is wrong?

**Comment by markkerzner** [comment]
The test data has pst files, and they contain 2000 emails

Mark Kerzner, Managing Partner, Elephant Scale <http://elephantscale.com/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1

**Comment by alexee** [comment]
@markkerzner 
Now outputs around 2400 lines. Please pull from my branch.

There were few problems - 1) readpst was not detected properly on OS X - /usr/bin/local is not in PATH by default, 2) Exceptions were swallowed in OsUtil.runCommand methods, I did some refactoring there.

I did not verify it on Linux, please check it.

**Comment by markkerzner** [comment]
I tested in Linux, it works. But do we have a test that verifies the number of output results? We should

**Comment by markkerzner** [comment]
Alex fixed it, Mark tested
