### ISSUE TITLE
Feature Request - Create processor plugin system

### ISSUE THREAD

**Issue by ajmcguire** [markkerzner/FreeEed#62]
Do we want to create a plugin system where as you add a Project Input, it asks you which processor to use.  The default will be the built in processor, but a dropdown list of any processors in the "plugin" directory will also be listed.

Some of the data I will be working with will be highly specialized and really does not belong in the main application.  Using the plugin system, I can write the specialized plugin without complicating the main processing.

This will also allow the ability to put a wrapper around a closed third-party application, allowing it to be used, but not requiring a license for the main project.  This may help with some of the other issues listed (Like PST password recovery and PST repair)

**Comment by markkerzner** [comment]
not now
