### ISSUE TITLE
Feature Request - Automatic Custodian Generation

### ISSUE THREAD

**Issue by ajmcguire** [markkerzner/FreeEed#64]
I have a number of repositories that are User home directories from a server.  Each first-level subfolder is the username of the Custodian of that folder.  Instead of adding each folder separately, I would like to add the top folder and set the custodian to %username%.  As it is staging/processing, it will switch the Custodian automatically to match the user folder it is currently in.

If you like this, I can add it.

**Comment by markkerzner** [comment]
not now
