### ISSUE TITLE
Feature Request - Have FreeEed automatically upload shmcloud config files to SolrCloud

### ISSUE THREAD

**Issue by ajmcguire** [markkerzner/FreeEed#65]
My last commit, switches to the Collections API if it detects SolrCloud instead of traditional Solr.  However one change is the you have to preload the shmcloud config into SolrCloud.  I run the below line to manually add these files, but we should automate the client to add them if they are not present.

./cloud-scripts/zkcli.sh -cmd upconfig -zkhost 127.0.0.1:9983 -confdir ~/FreeEed-dev/FreeEed/config/solr/shmcloud/conf -confname shmcloud

**Comment by markkerzner** [comment]
not now
